project:
  type: website

website:
  title: "Madi's Blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/madiyonash/
      - icon: linkedin
        href: https://linkedin.com/madison-yonash/
format:
  html:
    theme: solar
    css: styles.css



